version: '3.9'

services:
  backend:
    build:
      context: ./weather-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/weather-db
    depends_on:
      - mongo

  frontend:
    build:
      context: ./weather-frontend
    ports:
      - "3001:80"

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
